### ISSUE TITLE
Juicio Experto

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-turisteando-por-mexico#1]
[JuicioExperto.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-turisteando-por-mexico/files/13339802/JuicioExperto.pdf

**Comment by MariaJose-1007** [comment]
Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
